from connect import get_dgraph_client
from Queries.dgraph_queries import dgraph_r5_espacios_por_usuario_y_tipo_evento

client = get_dgraph_client()

dgraph_r5_espacios_por_usuario_y_tipo_evento(client)